### ISSUE TITLE
`group 'www-data' does not exist`

### ISSUE THREAD

**Issue by mizzunet** [ljanyst/peroxide#15]
`sudo useradd --system --no-create-home -g peroxide -G www-data peroxide` fails `group 'www-data' does not exist`.

* Yes, i do not have `www-data`. 
*  Though, I have `apache` package installed.
*  Should I add `www-data` group manually?
* `/etc/groups`: https://0x0.st/oBve.txt

Arch Linux 
Thank you so much for this fork :heart:

**Comment by ljanyst** [comment]
Yeah, that's there mostly because that group typically owns the X509 certificates. I will make the script smarter. Thanks for reporting.

**Comment by ljanyst** [comment]
It can't. Peroxide is the upstream ProtonBridge stripped down of all the desktop fluff
