### ISSUE TITLE
bad cert

### ISSUE THREAD

**Issue by r3k2** [ljanyst/peroxide#17]
Hello I have created a ramdon self-sign cert as in the README.md but I get 
```
peroxide[97761]: ERRO[Aug 29 11:46:34.050] cannot upgrade connection: remote error: tls: bad certificate  protocol=IMAP
```
as I can tell you mention you can use lets encrypt or a self-cert.. so why I am getting bad cert? do I need to pass an option to peroxide to ignore bad certs? this is on my desktop and laptop no central server no static ip and is inside my lan so cant have a real cert.

**Comment by ljanyst** [comment]
Of course you can have a real cert for a server without static IP and inside a LAN, just google it.

That said, self-signed certificates should still work. Please post the exact steps to reproduce your issue.

**Comment by ljanyst** [comment]
Does the common name (CN) match match the name your client is using to connect to the `peroxide`? If you're using `localhost` as the name of the server, the CN must match that. That's how X509 certificates ensure identity.

**Comment by r3k2** [comment]
Hello, ok yes I had by IP I usually try not to use localhost on anyconfig but 127.0.0.1 in any case I changed AERC my email client to use localhost now I get: protonmail: x509: certificate relies on legacy Common Name field, use SANs instead, lol what did I screw up now :)

**Comment by ljanyst** [comment]
AERC == The American Endurance Ride Conference? Also, please try to use punctuation.

Was the error printed by the client? What client?

**Comment by r3k2** [comment]
the client is "AERC",  https://aerc-mail.org/ and that is the error printed what I paste above.

**Comment by r3k2** [comment]
@ljanyst https://jfrog.com/knowledge-base/general-what-should-i-do-if-i-get-an-x509-certificate-relies-on-legacy-common-name-field-error/

**Comment by r3k2** [comment]
ok so I went and created an updated key with the new openssl method and deleted my account, relog into protonmail and now I get this when I open aerc "protonmail x509: certificate signed by unknown authority" this is my openssl command:
```
doas openssl req -new -newkey rsa:4048  -subj "/CN=localhost" -addext "subjectAltName = DNS:localhost" -days 365 -nodes -x509 -keyout key.pem -out cert.pem
```

**Comment by ljanyst** [comment]
Can you regenerate the certificate using the head of the master branch (https://github.com/ljanyst/peroxide/commit/4e913889566862f9bbed61c2bc74c5b9ae0ba93c) and retry?

**Comment by r3k2** [comment]
@ljanyst nope, this has to do with self-sign, this is why I went ahead and created it with openssl and forced the -addext  etc even like that it was giving me "protonmail: x509: certificate signed by unknown authority"  so you seen to have fixt the first issue, but the second issue still is there :/ I get "protonmail: x509: certificate signed by unknown authority"  so is not ignoring that is self-sign by a non-trusted authority.

**Comment by ljanyst** [comment]
Well, yes. The patch fixes the SAN issue. There's nothing I can do to help you with the other issue because that's how the X509 system of trust works by design. You have generated a certificate confirming the identity of your system and you signed it yourself. You're not a trusted authority on identifying systems. You have two options:

1. You force the client to accept a certificate signed by an unknown authority. There's usually an option to do that because that's not an unusual use case.
2. You add the certificate to the system's pool of trusted certificates. Here's an example of how to do it on Debian: https://grumpytechie.net/2020/02/25/adding-custom-root-ca-certificates-to-debian/

**Comment by r3k2** [comment]
ok, this is how you do it on Arch GNU/Linux in case someone searches for this issue.
```
doas trust anchor --store cert.pem
```
