### ISSUE TITLE
imap not sorted

### ISSUE THREAD

**Issue by r3k2** [ljanyst/peroxide#18]
Hello, I got this to work the other day on my 2 laptops and my desktop, all running linux and all before this running hydroxide, hydroxide drop imap support such is why I was recomended this proyect, for my protonmail accounts, for some reason and this never happend to me before the IMAP inbox folder for my protonmail account is all ramdonly sorted, not sorted by date like its always been, this did not happened with hydroxide or the official proxy before using hydroxide, I also use the same email client, at the start it was mutt and then I switched to "aerc email", when I type :sort date to sort by date it says this method is not allowed, I tried witrh my regular non-protonmail accounts Migadu(I recomend) etc this works fine.
Any idea/tip why this is happening?
thanks in advance

**Comment by ljanyst** [comment]
Peroxide is, in the essence, the same as the official proxy. It's a fork that is stripped of all the useless fluff, like GUIs, updaters, and other desktop integration. There is no reason it would behave differently than the official proton-bridge in this respect. What you see might be another manifestation of this problem: https://github.com/ProtonMail/proton-bridge/issues/220
