### ISSUE TITLE
Document that only paid subscriptions are supported

### ISSUE THREAD

**Issue by Jaakkonen** [ljanyst/peroxide#19]
Trying to login with a account that doesn't have a paid subscription results in error message
```
Failed to execute command: Login of account <username> failed: paid subscription plan is required
```

**Comment by hiddeninthesand** [comment]
Related to #16, the developer doesn't seem interested in fixing it so documenting in the README somewhere that it's paid only seems like a good idea. The current comparison to Hydroxide makes it easy to confuse if a paid subscription is necessary to use Peroxide.
